apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-lb
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}tcp{{ .Values.service.port }}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
