[constant]
nersc_user_id    = "<your nersc pid>"
nersc_user_group = "<the gid of the nersc project that you want to run this in>"

[zip]
name = "mysql"
tag = "9"
db_name = "science"
db_user_password = "pw"
db_root_password = "rpw"
db_user_name = "user"

